/********************************************************************************
** Form generated from reading UI file 'vehicleacpage.ui'
**
** Created: Thu Apr 19 11:15:44 2018
**      by: Qt User Interface Compiler version 4.6.3
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_VEHICLEACPAGE_H
#define UI_VEHICLEACPAGE_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_VehicleACPage
{
public:
    QPushButton *NextPageBtn;
    QLabel *lbl1_13;
    QLabel *lbl1;
    QLabel *lbl1_2;
    QLabel *lbl1_3;
    QLabel *lbl1_4;
    QLabel *lbl1_5;
    QLabel *lbl1_6;
    QLabel *lbl1_7;
    QLabel *lbl1_8;
    QLabel *lbl1_9;
    QLabel *lbl1_10;
    QLabel *lbl1_11;
    QLabel *lbl1_12;
    QLabel *ACModeTC1lbl;
    QLabel *ACReduceTC1lbl;
    QLabel *ACReduceMP1lbl;
    QLabel *ACModeMP1lbl;
    QLabel *ACReduceTC2lbl;
    QLabel *ACModeTC2lbl;
    QLabel *ACReduceM1lbl;
    QLabel *ACModeM1lbl;
    QLabel *ACReduceM2lbl;
    QLabel *ACModeM2lbl;
    QLabel *ACReduceMP2lbl;
    QLabel *ACModeMP2lbl;
    QLabel *ACControlTC2lbl;
    QLabel *ACControlM2lbl;
    QLabel *ACControlMP2lbl;
    QLabel *ACControlM1lbl;
    QLabel *ACControlTC1lbl;
    QLabel *ACControlMP1lbl;
    QLabel *TempTC2lbl;
    QLabel *TempM1lbl;
    QLabel *TempTC1lbl;
    QLabel *TempMP1lbl;
    QLabel *TempMP2lbl;
    QLabel *TempM2lbl;
    QLabel *lbl1_14;
    QLabel *YSJ1M2_1lbl;
    QLabel *YSJ1MP2_1lbl;
    QLabel *lbl1_15;
    QLabel *YSJ1TC1_1lbl;
    QLabel *YSJ1MP1_1lbl;
    QLabel *YSJ1M1_1lbl;
    QLabel *YSJ1TC2_1lbl;
    QLabel *YSJ1MP2_2lbl;
    QLabel *YSJ1M2_2lbl;
    QLabel *YSJ1TC2_2lbl;
    QLabel *YSJ1TC1_2lbl;
    QLabel *YSJ1MP1_2lbl;
    QLabel *YSJ1M1_2lbl;
    QLabel *YSJ2TC1_1lbl;
    QLabel *YSJ2MP2_1lbl;
    QLabel *YSJ2MP1_1lbl;
    QLabel *YSJ2TC1_2lbl;
    QLabel *YSJ2M2_1lbl;
    QLabel *YSJ2M2_2lbl;
    QLabel *YSJ2M1_2lbl;
    QLabel *lbl1_16;
    QLabel *YSJ2M1_1lbl;
    QLabel *YSJ2MP2_2lbl;
    QLabel *YSJ2TC2_1lbl;
    QLabel *YSJ2MP1_2lbl;
    QLabel *YSJ2TC2_2lbl;
    QLabel *LNFJ2TC2_1lbl;
    QLabel *LNFJ1M1_1lbl;
    QLabel *LNFJ1TC1_2lbl;
    QLabel *LNFJ1M1_2lbl;
    QLabel *LNFJ2MP2_1lbl;
    QLabel *lbl1_17;
    QLabel *LNFJ1MP1_1lbl;
    QLabel *LNFJ2TC1_2lbl;
    QLabel *LNFJ2M2_2lbl;
    QLabel *lbl1_18;
    QLabel *LNFJ1M2_2lbl;
    QLabel *LNFJ2M1_1lbl;
    QLabel *LNFJ1TC2_1lbl;
    QLabel *LNFJ1MP1_2lbl;
    QLabel *LNFJ1M2_1lbl;
    QLabel *LNFJ2TC1_1lbl;
    QLabel *LNFJ2TC2_2lbl;
    QLabel *LNFJ2MP1_1lbl;
    QLabel *LNFJ1TC1_1lbl;
    QLabel *LNFJ1TC2_2lbl;
    QLabel *LNFJ2M2_1lbl;
    QLabel *LNFJ2M1_2lbl;
    QLabel *LNFJ2MP1_2lbl;
    QLabel *LNFJ1MP2_1lbl;
    QLabel *LNFJ2MP2_2lbl;
    QLabel *LNFJ1MP2_2lbl;
    QLabel *TFJ2MP1_2lbl;
    QLabel *TFJ1M2_1lbl;
    QLabel *TFJ2M2_2lbl;
    QLabel *TFJ1TC2_2lbl;
    QLabel *TFJ1MP2_1lbl;
    QLabel *TFJ1MP1_2lbl;
    QLabel *TFJ1MP1_1lbl;
    QLabel *TFJ2MP2_2lbl;
    QLabel *TFJ2M1_1lbl;
    QLabel *TFJ1TC1_2lbl;
    QLabel *TFJ1TC2_1lbl;
    QLabel *TFJ2M1_2lbl;
    QLabel *TFJ1TC1_1lbl;
    QLabel *TFJ2TC1_1lbl;
    QLabel *TFJ1M2_2lbl;
    QLabel *TFJ2MP2_1lbl;
    QLabel *TFJ1M1_1lbl;
    QLabel *lbl1_19;
    QLabel *TFJ2MP1_1lbl;
    QLabel *TFJ1M1_2lbl;
    QLabel *TFJ2M2_1lbl;
    QLabel *TFJ2TC2_1lbl;
    QLabel *TFJ1MP2_2lbl;
    QLabel *lbl1_20;
    QLabel *TFJ2TC2_2lbl;
    QLabel *TFJ2TC1_2lbl;

    void setupUi(QWidget *VehicleACPage)
    {
        if (VehicleACPage->objectName().isEmpty())
            VehicleACPage->setObjectName(QString::fromUtf8("VehicleACPage"));
        VehicleACPage->resize(1024, 513);
        VehicleACPage->setStyleSheet(QString::fromUtf8("QWidget\n"
"{\n"
"	background-color:black;\n"
"}\n"
"QLabel\n"
"{\n"
"	font: 18px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";\n"
"	color:white;\n"
"background-color:green;\n"
"}\n"
"QPushButton\n"
"{\n"
"	background-color:orange ;\n"
"	border-top: 2px solid white;	\n"
"	border-left: 2px solid white;\n"
"}"));
        NextPageBtn = new QPushButton(VehicleACPage);
        NextPageBtn->setObjectName(QString::fromUtf8("NextPageBtn"));
        NextPageBtn->setGeometry(QRect(920, 320, 81, 51));
        NextPageBtn->setFocusPolicy(Qt::NoFocus);
        NextPageBtn->setStyleSheet(QString::fromUtf8("font:30px;\n"
"color:white;\n"
"background-color:brown;\n"
"border-radius:8px;"));
        lbl1_13 = new QLabel(VehicleACPage);
        lbl1_13->setObjectName(QString::fromUtf8("lbl1_13"));
        lbl1_13->setGeometry(QRect(910, 250, 101, 151));
        lbl1_13->setStyleSheet(QString::fromUtf8("background-color:lightgray;\n"
"border-radius:10px;\n"
"font:14px;\n"
"color:brown;"));
        lbl1_13->setAlignment(Qt::AlignCenter);
        lbl1 = new QLabel(VehicleACPage);
        lbl1->setObjectName(QString::fromUtf8("lbl1"));
        lbl1->setGeometry(QRect(20, 20, 131, 31));
        lbl1->setStyleSheet(QString::fromUtf8("background-color:black;"));
        lbl1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbl1_2 = new QLabel(VehicleACPage);
        lbl1_2->setObjectName(QString::fromUtf8("lbl1_2"));
        lbl1_2->setGeometry(QRect(20, 90, 131, 31));
        lbl1_2->setStyleSheet(QString::fromUtf8("background-color:black;"));
        lbl1_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbl1_3 = new QLabel(VehicleACPage);
        lbl1_3->setObjectName(QString::fromUtf8("lbl1_3"));
        lbl1_3->setGeometry(QRect(20, 160, 131, 31));
        lbl1_3->setStyleSheet(QString::fromUtf8("background-color:black;"));
        lbl1_3->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbl1_4 = new QLabel(VehicleACPage);
        lbl1_4->setObjectName(QString::fromUtf8("lbl1_4"));
        lbl1_4->setGeometry(QRect(20, 240, 91, 31));
        lbl1_4->setStyleSheet(QString::fromUtf8("background-color:black;"));
        lbl1_4->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbl1_5 = new QLabel(VehicleACPage);
        lbl1_5->setObjectName(QString::fromUtf8("lbl1_5"));
        lbl1_5->setGeometry(QRect(20, 330, 91, 31));
        lbl1_5->setStyleSheet(QString::fromUtf8("background-color:black;"));
        lbl1_5->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbl1_6 = new QLabel(VehicleACPage);
        lbl1_6->setObjectName(QString::fromUtf8("lbl1_6"));
        lbl1_6->setGeometry(QRect(20, 420, 91, 31));
        lbl1_6->setStyleSheet(QString::fromUtf8("background-color:black;"));
        lbl1_6->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lbl1_7 = new QLabel(VehicleACPage);
        lbl1_7->setObjectName(QString::fromUtf8("lbl1_7"));
        lbl1_7->setGeometry(QRect(130, 220, 31, 31));
        lbl1_7->setStyleSheet(QString::fromUtf8("background-color:black;"));
        lbl1_7->setAlignment(Qt::AlignCenter);
        lbl1_8 = new QLabel(VehicleACPage);
        lbl1_8->setObjectName(QString::fromUtf8("lbl1_8"));
        lbl1_8->setGeometry(QRect(130, 260, 31, 31));
        lbl1_8->setStyleSheet(QString::fromUtf8("background-color:black;"));
        lbl1_8->setAlignment(Qt::AlignCenter);
        lbl1_9 = new QLabel(VehicleACPage);
        lbl1_9->setObjectName(QString::fromUtf8("lbl1_9"));
        lbl1_9->setGeometry(QRect(130, 310, 31, 31));
        lbl1_9->setStyleSheet(QString::fromUtf8("background-color:black;"));
        lbl1_9->setAlignment(Qt::AlignCenter);
        lbl1_10 = new QLabel(VehicleACPage);
        lbl1_10->setObjectName(QString::fromUtf8("lbl1_10"));
        lbl1_10->setGeometry(QRect(130, 350, 31, 31));
        lbl1_10->setStyleSheet(QString::fromUtf8("background-color:black;"));
        lbl1_10->setAlignment(Qt::AlignCenter);
        lbl1_11 = new QLabel(VehicleACPage);
        lbl1_11->setObjectName(QString::fromUtf8("lbl1_11"));
        lbl1_11->setGeometry(QRect(130, 400, 31, 31));
        lbl1_11->setStyleSheet(QString::fromUtf8("background-color:black;"));
        lbl1_11->setAlignment(Qt::AlignCenter);
        lbl1_12 = new QLabel(VehicleACPage);
        lbl1_12->setObjectName(QString::fromUtf8("lbl1_12"));
        lbl1_12->setGeometry(QRect(130, 440, 31, 31));
        lbl1_12->setStyleSheet(QString::fromUtf8("background-color:black;"));
        lbl1_12->setAlignment(Qt::AlignCenter);
        ACModeTC1lbl = new QLabel(VehicleACPage);
        ACModeTC1lbl->setObjectName(QString::fromUtf8("ACModeTC1lbl"));
        ACModeTC1lbl->setGeometry(QRect(180, 20, 69, 31));
        ACModeTC1lbl->setStyleSheet(QString::fromUtf8("font:16px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        ACModeTC1lbl->setAlignment(Qt::AlignCenter);
        ACReduceTC1lbl = new QLabel(VehicleACPage);
        ACReduceTC1lbl->setObjectName(QString::fromUtf8("ACReduceTC1lbl"));
        ACReduceTC1lbl->setGeometry(QRect(250, 20, 21, 31));
        ACReduceTC1lbl->setStyleSheet(QString::fromUtf8("background-color:gray"));
        ACReduceTC1lbl->setAlignment(Qt::AlignCenter);
        ACReduceMP1lbl = new QLabel(VehicleACPage);
        ACReduceMP1lbl->setObjectName(QString::fromUtf8("ACReduceMP1lbl"));
        ACReduceMP1lbl->setGeometry(QRect(370, 20, 21, 31));
        ACReduceMP1lbl->setStyleSheet(QString::fromUtf8("background-color:gray"));
        ACReduceMP1lbl->setAlignment(Qt::AlignCenter);
        ACModeMP1lbl = new QLabel(VehicleACPage);
        ACModeMP1lbl->setObjectName(QString::fromUtf8("ACModeMP1lbl"));
        ACModeMP1lbl->setGeometry(QRect(300, 20, 69, 31));
        ACModeMP1lbl->setStyleSheet(QString::fromUtf8("font:16px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        ACModeMP1lbl->setAlignment(Qt::AlignCenter);
        ACReduceTC2lbl = new QLabel(VehicleACPage);
        ACReduceTC2lbl->setObjectName(QString::fromUtf8("ACReduceTC2lbl"));
        ACReduceTC2lbl->setGeometry(QRect(850, 20, 21, 31));
        ACReduceTC2lbl->setStyleSheet(QString::fromUtf8("background-color:gray"));
        ACReduceTC2lbl->setAlignment(Qt::AlignCenter);
        ACModeTC2lbl = new QLabel(VehicleACPage);
        ACModeTC2lbl->setObjectName(QString::fromUtf8("ACModeTC2lbl"));
        ACModeTC2lbl->setGeometry(QRect(780, 20, 69, 31));
        ACModeTC2lbl->setStyleSheet(QString::fromUtf8("font:16px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        ACModeTC2lbl->setAlignment(Qt::AlignCenter);
        ACReduceM1lbl = new QLabel(VehicleACPage);
        ACReduceM1lbl->setObjectName(QString::fromUtf8("ACReduceM1lbl"));
        ACReduceM1lbl->setGeometry(QRect(490, 20, 21, 31));
        ACReduceM1lbl->setStyleSheet(QString::fromUtf8("background-color:gray"));
        ACReduceM1lbl->setAlignment(Qt::AlignCenter);
        ACModeM1lbl = new QLabel(VehicleACPage);
        ACModeM1lbl->setObjectName(QString::fromUtf8("ACModeM1lbl"));
        ACModeM1lbl->setGeometry(QRect(420, 20, 69, 31));
        ACModeM1lbl->setStyleSheet(QString::fromUtf8("font:16px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        ACModeM1lbl->setAlignment(Qt::AlignCenter);
        ACReduceM2lbl = new QLabel(VehicleACPage);
        ACReduceM2lbl->setObjectName(QString::fromUtf8("ACReduceM2lbl"));
        ACReduceM2lbl->setGeometry(QRect(610, 20, 21, 31));
        ACReduceM2lbl->setStyleSheet(QString::fromUtf8("background-color:gray"));
        ACReduceM2lbl->setAlignment(Qt::AlignCenter);
        ACModeM2lbl = new QLabel(VehicleACPage);
        ACModeM2lbl->setObjectName(QString::fromUtf8("ACModeM2lbl"));
        ACModeM2lbl->setGeometry(QRect(540, 20, 69, 31));
        ACModeM2lbl->setStyleSheet(QString::fromUtf8("font:16px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        ACModeM2lbl->setAlignment(Qt::AlignCenter);
        ACReduceMP2lbl = new QLabel(VehicleACPage);
        ACReduceMP2lbl->setObjectName(QString::fromUtf8("ACReduceMP2lbl"));
        ACReduceMP2lbl->setGeometry(QRect(730, 20, 21, 31));
        ACReduceMP2lbl->setStyleSheet(QString::fromUtf8("background-color:gray"));
        ACReduceMP2lbl->setAlignment(Qt::AlignCenter);
        ACModeMP2lbl = new QLabel(VehicleACPage);
        ACModeMP2lbl->setObjectName(QString::fromUtf8("ACModeMP2lbl"));
        ACModeMP2lbl->setGeometry(QRect(660, 20, 69, 31));
        ACModeMP2lbl->setStyleSheet(QString::fromUtf8("font:16px, \"\345\276\256\350\275\257\351\233\205\351\273\221\";"));
        ACModeMP2lbl->setAlignment(Qt::AlignCenter);
        ACControlTC2lbl = new QLabel(VehicleACPage);
        ACControlTC2lbl->setObjectName(QString::fromUtf8("ACControlTC2lbl"));
        ACControlTC2lbl->setGeometry(QRect(780, 90, 91, 31));
        ACControlTC2lbl->setAlignment(Qt::AlignCenter);
        ACControlM2lbl = new QLabel(VehicleACPage);
        ACControlM2lbl->setObjectName(QString::fromUtf8("ACControlM2lbl"));
        ACControlM2lbl->setGeometry(QRect(540, 90, 91, 31));
        ACControlM2lbl->setAlignment(Qt::AlignCenter);
        ACControlMP2lbl = new QLabel(VehicleACPage);
        ACControlMP2lbl->setObjectName(QString::fromUtf8("ACControlMP2lbl"));
        ACControlMP2lbl->setGeometry(QRect(660, 90, 91, 31));
        ACControlMP2lbl->setAlignment(Qt::AlignCenter);
        ACControlM1lbl = new QLabel(VehicleACPage);
        ACControlM1lbl->setObjectName(QString::fromUtf8("ACControlM1lbl"));
        ACControlM1lbl->setGeometry(QRect(420, 90, 91, 31));
        ACControlM1lbl->setAlignment(Qt::AlignCenter);
        ACControlTC1lbl = new QLabel(VehicleACPage);
        ACControlTC1lbl->setObjectName(QString::fromUtf8("ACControlTC1lbl"));
        ACControlTC1lbl->setGeometry(QRect(180, 90, 91, 31));
        ACControlTC1lbl->setAlignment(Qt::AlignCenter);
        ACControlMP1lbl = new QLabel(VehicleACPage);
        ACControlMP1lbl->setObjectName(QString::fromUtf8("ACControlMP1lbl"));
        ACControlMP1lbl->setGeometry(QRect(300, 90, 91, 31));
        ACControlMP1lbl->setAlignment(Qt::AlignCenter);
        TempTC2lbl = new QLabel(VehicleACPage);
        TempTC2lbl->setObjectName(QString::fromUtf8("TempTC2lbl"));
        TempTC2lbl->setGeometry(QRect(790, 160, 71, 31));
        TempTC2lbl->setStyleSheet(QString::fromUtf8("background-color:blue;\n"
""));
        TempTC2lbl->setAlignment(Qt::AlignCenter);
        TempM1lbl = new QLabel(VehicleACPage);
        TempM1lbl->setObjectName(QString::fromUtf8("TempM1lbl"));
        TempM1lbl->setGeometry(QRect(430, 160, 71, 31));
        TempM1lbl->setStyleSheet(QString::fromUtf8("background-color:blue;\n"
""));
        TempM1lbl->setAlignment(Qt::AlignCenter);
        TempTC1lbl = new QLabel(VehicleACPage);
        TempTC1lbl->setObjectName(QString::fromUtf8("TempTC1lbl"));
        TempTC1lbl->setGeometry(QRect(190, 160, 71, 31));
        TempTC1lbl->setStyleSheet(QString::fromUtf8("background-color:blue;\n"
""));
        TempTC1lbl->setAlignment(Qt::AlignCenter);
        TempMP1lbl = new QLabel(VehicleACPage);
        TempMP1lbl->setObjectName(QString::fromUtf8("TempMP1lbl"));
        TempMP1lbl->setGeometry(QRect(310, 160, 71, 31));
        TempMP1lbl->setStyleSheet(QString::fromUtf8("background-color:blue;\n"
""));
        TempMP1lbl->setAlignment(Qt::AlignCenter);
        TempMP2lbl = new QLabel(VehicleACPage);
        TempMP2lbl->setObjectName(QString::fromUtf8("TempMP2lbl"));
        TempMP2lbl->setGeometry(QRect(670, 160, 71, 31));
        TempMP2lbl->setStyleSheet(QString::fromUtf8("background-color:blue;\n"
""));
        TempMP2lbl->setAlignment(Qt::AlignCenter);
        TempM2lbl = new QLabel(VehicleACPage);
        TempM2lbl->setObjectName(QString::fromUtf8("TempM2lbl"));
        TempM2lbl->setGeometry(QRect(550, 160, 71, 31));
        TempM2lbl->setStyleSheet(QString::fromUtf8("background-color:blue;\n"
""));
        TempM2lbl->setAlignment(Qt::AlignCenter);
        lbl1_14 = new QLabel(VehicleACPage);
        lbl1_14->setObjectName(QString::fromUtf8("lbl1_14"));
        lbl1_14->setGeometry(QRect(180, 175, 700, 2));
        lbl1_14->setStyleSheet(QString::fromUtf8("background-color:white;"));
        lbl1_14->setAlignment(Qt::AlignCenter);
        YSJ1M2_1lbl = new QLabel(VehicleACPage);
        YSJ1M2_1lbl->setObjectName(QString::fromUtf8("YSJ1M2_1lbl"));
        YSJ1M2_1lbl->setGeometry(QRect(590, 220, 30, 31));
        YSJ1M2_1lbl->setAlignment(Qt::AlignCenter);
        YSJ1MP2_1lbl = new QLabel(VehicleACPage);
        YSJ1MP2_1lbl->setObjectName(QString::fromUtf8("YSJ1MP2_1lbl"));
        YSJ1MP2_1lbl->setGeometry(QRect(710, 220, 30, 31));
        YSJ1MP2_1lbl->setAlignment(Qt::AlignCenter);
        lbl1_15 = new QLabel(VehicleACPage);
        lbl1_15->setObjectName(QString::fromUtf8("lbl1_15"));
        lbl1_15->setGeometry(QRect(180, 235, 700, 2));
        lbl1_15->setStyleSheet(QString::fromUtf8("background-color:white;"));
        lbl1_15->setAlignment(Qt::AlignCenter);
        YSJ1TC1_1lbl = new QLabel(VehicleACPage);
        YSJ1TC1_1lbl->setObjectName(QString::fromUtf8("YSJ1TC1_1lbl"));
        YSJ1TC1_1lbl->setGeometry(QRect(190, 220, 30, 31));
        YSJ1TC1_1lbl->setAlignment(Qt::AlignCenter);
        YSJ1MP1_1lbl = new QLabel(VehicleACPage);
        YSJ1MP1_1lbl->setObjectName(QString::fromUtf8("YSJ1MP1_1lbl"));
        YSJ1MP1_1lbl->setGeometry(QRect(310, 220, 30, 31));
        YSJ1MP1_1lbl->setAlignment(Qt::AlignCenter);
        YSJ1M1_1lbl = new QLabel(VehicleACPage);
        YSJ1M1_1lbl->setObjectName(QString::fromUtf8("YSJ1M1_1lbl"));
        YSJ1M1_1lbl->setGeometry(QRect(430, 220, 30, 31));
        YSJ1M1_1lbl->setAlignment(Qt::AlignCenter);
        YSJ1TC2_1lbl = new QLabel(VehicleACPage);
        YSJ1TC2_1lbl->setObjectName(QString::fromUtf8("YSJ1TC2_1lbl"));
        YSJ1TC2_1lbl->setGeometry(QRect(830, 220, 30, 31));
        YSJ1TC2_1lbl->setAlignment(Qt::AlignCenter);
        YSJ1MP2_2lbl = new QLabel(VehicleACPage);
        YSJ1MP2_2lbl->setObjectName(QString::fromUtf8("YSJ1MP2_2lbl"));
        YSJ1MP2_2lbl->setGeometry(QRect(670, 220, 30, 31));
        YSJ1MP2_2lbl->setAlignment(Qt::AlignCenter);
        YSJ1M2_2lbl = new QLabel(VehicleACPage);
        YSJ1M2_2lbl->setObjectName(QString::fromUtf8("YSJ1M2_2lbl"));
        YSJ1M2_2lbl->setGeometry(QRect(550, 220, 30, 31));
        YSJ1M2_2lbl->setAlignment(Qt::AlignCenter);
        YSJ1TC2_2lbl = new QLabel(VehicleACPage);
        YSJ1TC2_2lbl->setObjectName(QString::fromUtf8("YSJ1TC2_2lbl"));
        YSJ1TC2_2lbl->setGeometry(QRect(790, 220, 30, 31));
        YSJ1TC2_2lbl->setAlignment(Qt::AlignCenter);
        YSJ1TC1_2lbl = new QLabel(VehicleACPage);
        YSJ1TC1_2lbl->setObjectName(QString::fromUtf8("YSJ1TC1_2lbl"));
        YSJ1TC1_2lbl->setGeometry(QRect(230, 220, 30, 31));
        YSJ1TC1_2lbl->setAlignment(Qt::AlignCenter);
        YSJ1MP1_2lbl = new QLabel(VehicleACPage);
        YSJ1MP1_2lbl->setObjectName(QString::fromUtf8("YSJ1MP1_2lbl"));
        YSJ1MP1_2lbl->setGeometry(QRect(350, 220, 30, 31));
        YSJ1MP1_2lbl->setAlignment(Qt::AlignCenter);
        YSJ1M1_2lbl = new QLabel(VehicleACPage);
        YSJ1M1_2lbl->setObjectName(QString::fromUtf8("YSJ1M1_2lbl"));
        YSJ1M1_2lbl->setGeometry(QRect(470, 220, 30, 31));
        YSJ1M1_2lbl->setAlignment(Qt::AlignCenter);
        YSJ2TC1_1lbl = new QLabel(VehicleACPage);
        YSJ2TC1_1lbl->setObjectName(QString::fromUtf8("YSJ2TC1_1lbl"));
        YSJ2TC1_1lbl->setGeometry(QRect(190, 260, 30, 31));
        YSJ2TC1_1lbl->setAlignment(Qt::AlignCenter);
        YSJ2MP2_1lbl = new QLabel(VehicleACPage);
        YSJ2MP2_1lbl->setObjectName(QString::fromUtf8("YSJ2MP2_1lbl"));
        YSJ2MP2_1lbl->setGeometry(QRect(710, 260, 30, 31));
        YSJ2MP2_1lbl->setAlignment(Qt::AlignCenter);
        YSJ2MP1_1lbl = new QLabel(VehicleACPage);
        YSJ2MP1_1lbl->setObjectName(QString::fromUtf8("YSJ2MP1_1lbl"));
        YSJ2MP1_1lbl->setGeometry(QRect(310, 260, 30, 31));
        YSJ2MP1_1lbl->setAlignment(Qt::AlignCenter);
        YSJ2TC1_2lbl = new QLabel(VehicleACPage);
        YSJ2TC1_2lbl->setObjectName(QString::fromUtf8("YSJ2TC1_2lbl"));
        YSJ2TC1_2lbl->setGeometry(QRect(230, 260, 30, 31));
        YSJ2TC1_2lbl->setAlignment(Qt::AlignCenter);
        YSJ2M2_1lbl = new QLabel(VehicleACPage);
        YSJ2M2_1lbl->setObjectName(QString::fromUtf8("YSJ2M2_1lbl"));
        YSJ2M2_1lbl->setGeometry(QRect(590, 260, 30, 31));
        YSJ2M2_1lbl->setAlignment(Qt::AlignCenter);
        YSJ2M2_2lbl = new QLabel(VehicleACPage);
        YSJ2M2_2lbl->setObjectName(QString::fromUtf8("YSJ2M2_2lbl"));
        YSJ2M2_2lbl->setGeometry(QRect(550, 260, 30, 31));
        YSJ2M2_2lbl->setAlignment(Qt::AlignCenter);
        YSJ2M1_2lbl = new QLabel(VehicleACPage);
        YSJ2M1_2lbl->setObjectName(QString::fromUtf8("YSJ2M1_2lbl"));
        YSJ2M1_2lbl->setGeometry(QRect(470, 260, 30, 31));
        YSJ2M1_2lbl->setAlignment(Qt::AlignCenter);
        lbl1_16 = new QLabel(VehicleACPage);
        lbl1_16->setObjectName(QString::fromUtf8("lbl1_16"));
        lbl1_16->setGeometry(QRect(180, 275, 700, 2));
        lbl1_16->setStyleSheet(QString::fromUtf8("background-color:white;"));
        lbl1_16->setAlignment(Qt::AlignCenter);
        YSJ2M1_1lbl = new QLabel(VehicleACPage);
        YSJ2M1_1lbl->setObjectName(QString::fromUtf8("YSJ2M1_1lbl"));
        YSJ2M1_1lbl->setGeometry(QRect(430, 260, 30, 31));
        YSJ2M1_1lbl->setAlignment(Qt::AlignCenter);
        YSJ2MP2_2lbl = new QLabel(VehicleACPage);
        YSJ2MP2_2lbl->setObjectName(QString::fromUtf8("YSJ2MP2_2lbl"));
        YSJ2MP2_2lbl->setGeometry(QRect(670, 260, 30, 31));
        YSJ2MP2_2lbl->setAlignment(Qt::AlignCenter);
        YSJ2TC2_1lbl = new QLabel(VehicleACPage);
        YSJ2TC2_1lbl->setObjectName(QString::fromUtf8("YSJ2TC2_1lbl"));
        YSJ2TC2_1lbl->setGeometry(QRect(830, 260, 30, 31));
        YSJ2TC2_1lbl->setAlignment(Qt::AlignCenter);
        YSJ2MP1_2lbl = new QLabel(VehicleACPage);
        YSJ2MP1_2lbl->setObjectName(QString::fromUtf8("YSJ2MP1_2lbl"));
        YSJ2MP1_2lbl->setGeometry(QRect(350, 260, 30, 31));
        YSJ2MP1_2lbl->setAlignment(Qt::AlignCenter);
        YSJ2TC2_2lbl = new QLabel(VehicleACPage);
        YSJ2TC2_2lbl->setObjectName(QString::fromUtf8("YSJ2TC2_2lbl"));
        YSJ2TC2_2lbl->setGeometry(QRect(790, 260, 30, 31));
        YSJ2TC2_2lbl->setAlignment(Qt::AlignCenter);
        LNFJ2TC2_1lbl = new QLabel(VehicleACPage);
        LNFJ2TC2_1lbl->setObjectName(QString::fromUtf8("LNFJ2TC2_1lbl"));
        LNFJ2TC2_1lbl->setGeometry(QRect(830, 350, 30, 31));
        LNFJ2TC2_1lbl->setAlignment(Qt::AlignCenter);
        LNFJ1M1_1lbl = new QLabel(VehicleACPage);
        LNFJ1M1_1lbl->setObjectName(QString::fromUtf8("LNFJ1M1_1lbl"));
        LNFJ1M1_1lbl->setGeometry(QRect(430, 310, 30, 31));
        LNFJ1M1_1lbl->setAlignment(Qt::AlignCenter);
        LNFJ1TC1_2lbl = new QLabel(VehicleACPage);
        LNFJ1TC1_2lbl->setObjectName(QString::fromUtf8("LNFJ1TC1_2lbl"));
        LNFJ1TC1_2lbl->setGeometry(QRect(230, 310, 30, 31));
        LNFJ1TC1_2lbl->setAlignment(Qt::AlignCenter);
        LNFJ1M1_2lbl = new QLabel(VehicleACPage);
        LNFJ1M1_2lbl->setObjectName(QString::fromUtf8("LNFJ1M1_2lbl"));
        LNFJ1M1_2lbl->setGeometry(QRect(470, 310, 30, 31));
        LNFJ1M1_2lbl->setAlignment(Qt::AlignCenter);
        LNFJ2MP2_1lbl = new QLabel(VehicleACPage);
        LNFJ2MP2_1lbl->setObjectName(QString::fromUtf8("LNFJ2MP2_1lbl"));
        LNFJ2MP2_1lbl->setGeometry(QRect(710, 350, 30, 31));
        LNFJ2MP2_1lbl->setAlignment(Qt::AlignCenter);
        lbl1_17 = new QLabel(VehicleACPage);
        lbl1_17->setObjectName(QString::fromUtf8("lbl1_17"));
        lbl1_17->setGeometry(QRect(180, 325, 700, 2));
        lbl1_17->setStyleSheet(QString::fromUtf8("background-color:white;"));
        lbl1_17->setAlignment(Qt::AlignCenter);
        LNFJ1MP1_1lbl = new QLabel(VehicleACPage);
        LNFJ1MP1_1lbl->setObjectName(QString::fromUtf8("LNFJ1MP1_1lbl"));
        LNFJ1MP1_1lbl->setGeometry(QRect(310, 310, 30, 31));
        LNFJ1MP1_1lbl->setAlignment(Qt::AlignCenter);
        LNFJ2TC1_2lbl = new QLabel(VehicleACPage);
        LNFJ2TC1_2lbl->setObjectName(QString::fromUtf8("LNFJ2TC1_2lbl"));
        LNFJ2TC1_2lbl->setGeometry(QRect(230, 350, 30, 31));
        LNFJ2TC1_2lbl->setAlignment(Qt::AlignCenter);
        LNFJ2M2_2lbl = new QLabel(VehicleACPage);
        LNFJ2M2_2lbl->setObjectName(QString::fromUtf8("LNFJ2M2_2lbl"));
        LNFJ2M2_2lbl->setGeometry(QRect(550, 350, 30, 31));
        LNFJ2M2_2lbl->setAlignment(Qt::AlignCenter);
        lbl1_18 = new QLabel(VehicleACPage);
        lbl1_18->setObjectName(QString::fromUtf8("lbl1_18"));
        lbl1_18->setGeometry(QRect(180, 365, 700, 2));
        lbl1_18->setStyleSheet(QString::fromUtf8("background-color:white;"));
        lbl1_18->setAlignment(Qt::AlignCenter);
        LNFJ1M2_2lbl = new QLabel(VehicleACPage);
        LNFJ1M2_2lbl->setObjectName(QString::fromUtf8("LNFJ1M2_2lbl"));
        LNFJ1M2_2lbl->setGeometry(QRect(550, 310, 30, 31));
        LNFJ1M2_2lbl->setAlignment(Qt::AlignCenter);
        LNFJ2M1_1lbl = new QLabel(VehicleACPage);
        LNFJ2M1_1lbl->setObjectName(QString::fromUtf8("LNFJ2M1_1lbl"));
        LNFJ2M1_1lbl->setGeometry(QRect(430, 350, 30, 31));
        LNFJ2M1_1lbl->setAlignment(Qt::AlignCenter);
        LNFJ1TC2_1lbl = new QLabel(VehicleACPage);
        LNFJ1TC2_1lbl->setObjectName(QString::fromUtf8("LNFJ1TC2_1lbl"));
        LNFJ1TC2_1lbl->setGeometry(QRect(830, 310, 30, 31));
        LNFJ1TC2_1lbl->setAlignment(Qt::AlignCenter);
        LNFJ1MP1_2lbl = new QLabel(VehicleACPage);
        LNFJ1MP1_2lbl->setObjectName(QString::fromUtf8("LNFJ1MP1_2lbl"));
        LNFJ1MP1_2lbl->setGeometry(QRect(350, 310, 30, 31));
        LNFJ1MP1_2lbl->setAlignment(Qt::AlignCenter);
        LNFJ1M2_1lbl = new QLabel(VehicleACPage);
        LNFJ1M2_1lbl->setObjectName(QString::fromUtf8("LNFJ1M2_1lbl"));
        LNFJ1M2_1lbl->setGeometry(QRect(590, 310, 30, 31));
        LNFJ1M2_1lbl->setAlignment(Qt::AlignCenter);
        LNFJ2TC1_1lbl = new QLabel(VehicleACPage);
        LNFJ2TC1_1lbl->setObjectName(QString::fromUtf8("LNFJ2TC1_1lbl"));
        LNFJ2TC1_1lbl->setGeometry(QRect(190, 350, 30, 31));
        LNFJ2TC1_1lbl->setAlignment(Qt::AlignCenter);
        LNFJ2TC2_2lbl = new QLabel(VehicleACPage);
        LNFJ2TC2_2lbl->setObjectName(QString::fromUtf8("LNFJ2TC2_2lbl"));
        LNFJ2TC2_2lbl->setGeometry(QRect(790, 350, 30, 31));
        LNFJ2TC2_2lbl->setAlignment(Qt::AlignCenter);
        LNFJ2MP1_1lbl = new QLabel(VehicleACPage);
        LNFJ2MP1_1lbl->setObjectName(QString::fromUtf8("LNFJ2MP1_1lbl"));
        LNFJ2MP1_1lbl->setGeometry(QRect(310, 350, 30, 31));
        LNFJ2MP1_1lbl->setAlignment(Qt::AlignCenter);
        LNFJ1TC1_1lbl = new QLabel(VehicleACPage);
        LNFJ1TC1_1lbl->setObjectName(QString::fromUtf8("LNFJ1TC1_1lbl"));
        LNFJ1TC1_1lbl->setGeometry(QRect(190, 310, 30, 31));
        LNFJ1TC1_1lbl->setAlignment(Qt::AlignCenter);
        LNFJ1TC2_2lbl = new QLabel(VehicleACPage);
        LNFJ1TC2_2lbl->setObjectName(QString::fromUtf8("LNFJ1TC2_2lbl"));
        LNFJ1TC2_2lbl->setGeometry(QRect(790, 310, 30, 31));
        LNFJ1TC2_2lbl->setAlignment(Qt::AlignCenter);
        LNFJ2M2_1lbl = new QLabel(VehicleACPage);
        LNFJ2M2_1lbl->setObjectName(QString::fromUtf8("LNFJ2M2_1lbl"));
        LNFJ2M2_1lbl->setGeometry(QRect(590, 350, 30, 31));
        LNFJ2M2_1lbl->setAlignment(Qt::AlignCenter);
        LNFJ2M1_2lbl = new QLabel(VehicleACPage);
        LNFJ2M1_2lbl->setObjectName(QString::fromUtf8("LNFJ2M1_2lbl"));
        LNFJ2M1_2lbl->setGeometry(QRect(470, 350, 30, 31));
        LNFJ2M1_2lbl->setAlignment(Qt::AlignCenter);
        LNFJ2MP1_2lbl = new QLabel(VehicleACPage);
        LNFJ2MP1_2lbl->setObjectName(QString::fromUtf8("LNFJ2MP1_2lbl"));
        LNFJ2MP1_2lbl->setGeometry(QRect(350, 350, 30, 31));
        LNFJ2MP1_2lbl->setAlignment(Qt::AlignCenter);
        LNFJ1MP2_1lbl = new QLabel(VehicleACPage);
        LNFJ1MP2_1lbl->setObjectName(QString::fromUtf8("LNFJ1MP2_1lbl"));
        LNFJ1MP2_1lbl->setGeometry(QRect(710, 310, 30, 31));
        LNFJ1MP2_1lbl->setAlignment(Qt::AlignCenter);
        LNFJ2MP2_2lbl = new QLabel(VehicleACPage);
        LNFJ2MP2_2lbl->setObjectName(QString::fromUtf8("LNFJ2MP2_2lbl"));
        LNFJ2MP2_2lbl->setGeometry(QRect(670, 350, 30, 31));
        LNFJ2MP2_2lbl->setAlignment(Qt::AlignCenter);
        LNFJ1MP2_2lbl = new QLabel(VehicleACPage);
        LNFJ1MP2_2lbl->setObjectName(QString::fromUtf8("LNFJ1MP2_2lbl"));
        LNFJ1MP2_2lbl->setGeometry(QRect(670, 310, 30, 31));
        LNFJ1MP2_2lbl->setAlignment(Qt::AlignCenter);
        TFJ2MP1_2lbl = new QLabel(VehicleACPage);
        TFJ2MP1_2lbl->setObjectName(QString::fromUtf8("TFJ2MP1_2lbl"));
        TFJ2MP1_2lbl->setGeometry(QRect(350, 440, 30, 31));
        TFJ2MP1_2lbl->setAlignment(Qt::AlignCenter);
        TFJ1M2_1lbl = new QLabel(VehicleACPage);
        TFJ1M2_1lbl->setObjectName(QString::fromUtf8("TFJ1M2_1lbl"));
        TFJ1M2_1lbl->setGeometry(QRect(590, 400, 30, 31));
        TFJ1M2_1lbl->setAlignment(Qt::AlignCenter);
        TFJ2M2_2lbl = new QLabel(VehicleACPage);
        TFJ2M2_2lbl->setObjectName(QString::fromUtf8("TFJ2M2_2lbl"));
        TFJ2M2_2lbl->setGeometry(QRect(550, 440, 30, 31));
        TFJ2M2_2lbl->setAlignment(Qt::AlignCenter);
        TFJ1TC2_2lbl = new QLabel(VehicleACPage);
        TFJ1TC2_2lbl->setObjectName(QString::fromUtf8("TFJ1TC2_2lbl"));
        TFJ1TC2_2lbl->setGeometry(QRect(790, 400, 30, 31));
        TFJ1TC2_2lbl->setAlignment(Qt::AlignCenter);
        TFJ1MP2_1lbl = new QLabel(VehicleACPage);
        TFJ1MP2_1lbl->setObjectName(QString::fromUtf8("TFJ1MP2_1lbl"));
        TFJ1MP2_1lbl->setGeometry(QRect(710, 400, 30, 31));
        TFJ1MP2_1lbl->setAlignment(Qt::AlignCenter);
        TFJ1MP1_2lbl = new QLabel(VehicleACPage);
        TFJ1MP1_2lbl->setObjectName(QString::fromUtf8("TFJ1MP1_2lbl"));
        TFJ1MP1_2lbl->setGeometry(QRect(350, 400, 30, 31));
        TFJ1MP1_2lbl->setAlignment(Qt::AlignCenter);
        TFJ1MP1_1lbl = new QLabel(VehicleACPage);
        TFJ1MP1_1lbl->setObjectName(QString::fromUtf8("TFJ1MP1_1lbl"));
        TFJ1MP1_1lbl->setGeometry(QRect(310, 400, 30, 31));
        TFJ1MP1_1lbl->setAlignment(Qt::AlignCenter);
        TFJ2MP2_2lbl = new QLabel(VehicleACPage);
        TFJ2MP2_2lbl->setObjectName(QString::fromUtf8("TFJ2MP2_2lbl"));
        TFJ2MP2_2lbl->setGeometry(QRect(670, 440, 30, 31));
        TFJ2MP2_2lbl->setAlignment(Qt::AlignCenter);
        TFJ2M1_1lbl = new QLabel(VehicleACPage);
        TFJ2M1_1lbl->setObjectName(QString::fromUtf8("TFJ2M1_1lbl"));
        TFJ2M1_1lbl->setGeometry(QRect(430, 440, 30, 31));
        TFJ2M1_1lbl->setAlignment(Qt::AlignCenter);
        TFJ1TC1_2lbl = new QLabel(VehicleACPage);
        TFJ1TC1_2lbl->setObjectName(QString::fromUtf8("TFJ1TC1_2lbl"));
        TFJ1TC1_2lbl->setGeometry(QRect(230, 400, 30, 31));
        TFJ1TC1_2lbl->setAlignment(Qt::AlignCenter);
        TFJ1TC2_1lbl = new QLabel(VehicleACPage);
        TFJ1TC2_1lbl->setObjectName(QString::fromUtf8("TFJ1TC2_1lbl"));
        TFJ1TC2_1lbl->setGeometry(QRect(830, 400, 30, 31));
        TFJ1TC2_1lbl->setAlignment(Qt::AlignCenter);
        TFJ2M1_2lbl = new QLabel(VehicleACPage);
        TFJ2M1_2lbl->setObjectName(QString::fromUtf8("TFJ2M1_2lbl"));
        TFJ2M1_2lbl->setGeometry(QRect(470, 440, 30, 31));
        TFJ2M1_2lbl->setAlignment(Qt::AlignCenter);
        TFJ1TC1_1lbl = new QLabel(VehicleACPage);
        TFJ1TC1_1lbl->setObjectName(QString::fromUtf8("TFJ1TC1_1lbl"));
        TFJ1TC1_1lbl->setGeometry(QRect(190, 400, 30, 31));
        TFJ1TC1_1lbl->setAlignment(Qt::AlignCenter);
        TFJ2TC1_1lbl = new QLabel(VehicleACPage);
        TFJ2TC1_1lbl->setObjectName(QString::fromUtf8("TFJ2TC1_1lbl"));
        TFJ2TC1_1lbl->setGeometry(QRect(190, 440, 30, 31));
        TFJ2TC1_1lbl->setAlignment(Qt::AlignCenter);
        TFJ1M2_2lbl = new QLabel(VehicleACPage);
        TFJ1M2_2lbl->setObjectName(QString::fromUtf8("TFJ1M2_2lbl"));
        TFJ1M2_2lbl->setGeometry(QRect(550, 400, 30, 31));
        TFJ1M2_2lbl->setAlignment(Qt::AlignCenter);
        TFJ2MP2_1lbl = new QLabel(VehicleACPage);
        TFJ2MP2_1lbl->setObjectName(QString::fromUtf8("TFJ2MP2_1lbl"));
        TFJ2MP2_1lbl->setGeometry(QRect(710, 440, 30, 31));
        TFJ2MP2_1lbl->setAlignment(Qt::AlignCenter);
        TFJ1M1_1lbl = new QLabel(VehicleACPage);
        TFJ1M1_1lbl->setObjectName(QString::fromUtf8("TFJ1M1_1lbl"));
        TFJ1M1_1lbl->setGeometry(QRect(430, 400, 30, 31));
        TFJ1M1_1lbl->setAlignment(Qt::AlignCenter);
        lbl1_19 = new QLabel(VehicleACPage);
        lbl1_19->setObjectName(QString::fromUtf8("lbl1_19"));
        lbl1_19->setGeometry(QRect(180, 415, 700, 2));
        lbl1_19->setStyleSheet(QString::fromUtf8("background-color:white;"));
        lbl1_19->setAlignment(Qt::AlignCenter);
        TFJ2MP1_1lbl = new QLabel(VehicleACPage);
        TFJ2MP1_1lbl->setObjectName(QString::fromUtf8("TFJ2MP1_1lbl"));
        TFJ2MP1_1lbl->setGeometry(QRect(310, 440, 30, 31));
        TFJ2MP1_1lbl->setAlignment(Qt::AlignCenter);
        TFJ1M1_2lbl = new QLabel(VehicleACPage);
        TFJ1M1_2lbl->setObjectName(QString::fromUtf8("TFJ1M1_2lbl"));
        TFJ1M1_2lbl->setGeometry(QRect(470, 400, 30, 31));
        TFJ1M1_2lbl->setAlignment(Qt::AlignCenter);
        TFJ2M2_1lbl = new QLabel(VehicleACPage);
        TFJ2M2_1lbl->setObjectName(QString::fromUtf8("TFJ2M2_1lbl"));
        TFJ2M2_1lbl->setGeometry(QRect(590, 440, 30, 31));
        TFJ2M2_1lbl->setAlignment(Qt::AlignCenter);
        TFJ2TC2_1lbl = new QLabel(VehicleACPage);
        TFJ2TC2_1lbl->setObjectName(QString::fromUtf8("TFJ2TC2_1lbl"));
        TFJ2TC2_1lbl->setGeometry(QRect(830, 440, 30, 31));
        TFJ2TC2_1lbl->setAlignment(Qt::AlignCenter);
        TFJ1MP2_2lbl = new QLabel(VehicleACPage);
        TFJ1MP2_2lbl->setObjectName(QString::fromUtf8("TFJ1MP2_2lbl"));
        TFJ1MP2_2lbl->setGeometry(QRect(670, 400, 30, 31));
        TFJ1MP2_2lbl->setAlignment(Qt::AlignCenter);
        lbl1_20 = new QLabel(VehicleACPage);
        lbl1_20->setObjectName(QString::fromUtf8("lbl1_20"));
        lbl1_20->setGeometry(QRect(180, 455, 700, 2));
        lbl1_20->setStyleSheet(QString::fromUtf8("background-color:white;"));
        lbl1_20->setAlignment(Qt::AlignCenter);
        TFJ2TC2_2lbl = new QLabel(VehicleACPage);
        TFJ2TC2_2lbl->setObjectName(QString::fromUtf8("TFJ2TC2_2lbl"));
        TFJ2TC2_2lbl->setGeometry(QRect(790, 440, 30, 31));
        TFJ2TC2_2lbl->setAlignment(Qt::AlignCenter);
        TFJ2TC1_2lbl = new QLabel(VehicleACPage);
        TFJ2TC1_2lbl->setObjectName(QString::fromUtf8("TFJ2TC1_2lbl"));
        TFJ2TC1_2lbl->setGeometry(QRect(230, 440, 30, 31));
        TFJ2TC1_2lbl->setAlignment(Qt::AlignCenter);
        lbl1_13->raise();
        lbl1_15->raise();
        lbl1_18->raise();
        lbl1_19->raise();
        lbl1_17->raise();
        lbl1_16->raise();
        lbl1_20->raise();
        lbl1_14->raise();
        NextPageBtn->raise();
        lbl1->raise();
        lbl1_2->raise();
        lbl1_3->raise();
        lbl1_4->raise();
        lbl1_5->raise();
        lbl1_6->raise();
        lbl1_7->raise();
        lbl1_8->raise();
        lbl1_9->raise();
        lbl1_10->raise();
        lbl1_11->raise();
        lbl1_12->raise();
        ACModeTC1lbl->raise();
        ACReduceTC1lbl->raise();
        ACReduceMP1lbl->raise();
        ACModeMP1lbl->raise();
        ACReduceTC2lbl->raise();
        ACModeTC2lbl->raise();
        ACReduceM1lbl->raise();
        ACModeM1lbl->raise();
        ACReduceM2lbl->raise();
        ACModeM2lbl->raise();
        ACReduceMP2lbl->raise();
        ACModeMP2lbl->raise();
        ACControlTC2lbl->raise();
        ACControlM2lbl->raise();
        ACControlMP2lbl->raise();
        ACControlM1lbl->raise();
        ACControlTC1lbl->raise();
        ACControlMP1lbl->raise();
        TempTC2lbl->raise();
        TempM1lbl->raise();
        TempTC1lbl->raise();
        TempMP1lbl->raise();
        TempMP2lbl->raise();
        TempM2lbl->raise();
        YSJ1M2_1lbl->raise();
        YSJ1MP2_1lbl->raise();
        YSJ1TC1_1lbl->raise();
        YSJ1MP1_1lbl->raise();
        YSJ1M1_1lbl->raise();
        YSJ1TC2_1lbl->raise();
        YSJ1MP2_2lbl->raise();
        YSJ1M2_2lbl->raise();
        YSJ1TC2_2lbl->raise();
        YSJ1TC1_2lbl->raise();
        YSJ1MP1_2lbl->raise();
        YSJ1M1_2lbl->raise();
        YSJ2TC1_1lbl->raise();
        YSJ2MP2_1lbl->raise();
        YSJ2MP1_1lbl->raise();
        YSJ2TC1_2lbl->raise();
        YSJ2M2_1lbl->raise();
        YSJ2M2_2lbl->raise();
        YSJ2M1_2lbl->raise();
        YSJ2M1_1lbl->raise();
        YSJ2MP2_2lbl->raise();
        YSJ2TC2_1lbl->raise();
        YSJ2MP1_2lbl->raise();
        YSJ2TC2_2lbl->raise();
        LNFJ2TC2_1lbl->raise();
        LNFJ1M1_1lbl->raise();
        LNFJ1TC1_2lbl->raise();
        LNFJ1M1_2lbl->raise();
        LNFJ2MP2_1lbl->raise();
        LNFJ1MP1_1lbl->raise();
        LNFJ2TC1_2lbl->raise();
        LNFJ2M2_2lbl->raise();
        LNFJ1M2_2lbl->raise();
        LNFJ2M1_1lbl->raise();
        LNFJ1TC2_1lbl->raise();
        LNFJ1MP1_2lbl->raise();
        LNFJ1M2_1lbl->raise();
        LNFJ2TC1_1lbl->raise();
        LNFJ2TC2_2lbl->raise();
        LNFJ2MP1_1lbl->raise();
        LNFJ1TC1_1lbl->raise();
        LNFJ1TC2_2lbl->raise();
        LNFJ2M2_1lbl->raise();
        LNFJ2M1_2lbl->raise();
        LNFJ2MP1_2lbl->raise();
        LNFJ1MP2_1lbl->raise();
        LNFJ2MP2_2lbl->raise();
        LNFJ1MP2_2lbl->raise();
        TFJ2MP1_2lbl->raise();
        TFJ1M2_1lbl->raise();
        TFJ2M2_2lbl->raise();
        TFJ1TC2_2lbl->raise();
        TFJ1MP2_1lbl->raise();
        TFJ1MP1_2lbl->raise();
        TFJ1MP1_1lbl->raise();
        TFJ2MP2_2lbl->raise();
        TFJ2M1_1lbl->raise();
        TFJ1TC1_2lbl->raise();
        TFJ1TC2_1lbl->raise();
        TFJ2M1_2lbl->raise();
        TFJ1TC1_1lbl->raise();
        TFJ2TC1_1lbl->raise();
        TFJ1M2_2lbl->raise();
        TFJ2MP2_1lbl->raise();
        TFJ1M1_1lbl->raise();
        TFJ2MP1_1lbl->raise();
        TFJ1M1_2lbl->raise();
        TFJ2M2_1lbl->raise();
        TFJ2TC2_1lbl->raise();
        TFJ1MP2_2lbl->raise();
        TFJ2TC2_2lbl->raise();
        TFJ2TC1_2lbl->raise();

        retranslateUi(VehicleACPage);

        QMetaObject::connectSlotsByName(VehicleACPage);
    } // setupUi

    void retranslateUi(QWidget *VehicleACPage)
    {
        VehicleACPage->setWindowTitle(QApplication::translate("VehicleACPage", "Form", 0, QApplication::UnicodeUTF8));
        NextPageBtn->setText(QApplication::translate("VehicleACPage", "\342\226\274", 0, QApplication::UnicodeUTF8));
        lbl1_13->setText(QApplication::translate("VehicleACPage", "\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"\347\254\2541\351\241\265/\345\205\2612\351\241\265", 0, QApplication::UnicodeUTF8));
        lbl1->setText(QApplication::translate("VehicleACPage", "\347\251\272\350\260\203\346\250\241\345\274\217/\345\207\217\350\275\275", 0, QApplication::UnicodeUTF8));
        lbl1_2->setText(QApplication::translate("VehicleACPage", "\346\216\247\345\210\266\346\250\241\345\274\217", 0, QApplication::UnicodeUTF8));
        lbl1_3->setText(QApplication::translate("VehicleACPage", "\345\275\223\345\211\215\346\270\251\345\272\246(\342\204\203)", 0, QApplication::UnicodeUTF8));
        lbl1_4->setText(QApplication::translate("VehicleACPage", "\345\216\213\347\274\251\346\234\272", 0, QApplication::UnicodeUTF8));
        lbl1_5->setText(QApplication::translate("VehicleACPage", "\345\206\267\345\207\235\351\243\216\346\234\272", 0, QApplication::UnicodeUTF8));
        lbl1_6->setText(QApplication::translate("VehicleACPage", "\351\200\232\351\243\216\346\234\272", 0, QApplication::UnicodeUTF8));
        lbl1_7->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        lbl1_8->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        lbl1_9->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        lbl1_10->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        lbl1_11->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        lbl1_12->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        ACModeTC1lbl->setText(QApplication::translate("VehicleACPage", "\350\207\252\345\206\267", 0, QApplication::UnicodeUTF8));
        ACReduceTC1lbl->setText(QString());
        ACReduceMP1lbl->setText(QString());
        ACModeMP1lbl->setText(QApplication::translate("VehicleACPage", "\350\207\252\345\206\267", 0, QApplication::UnicodeUTF8));
        ACReduceTC2lbl->setText(QString());
        ACModeTC2lbl->setText(QApplication::translate("VehicleACPage", "\350\207\252\345\206\267", 0, QApplication::UnicodeUTF8));
        ACReduceM1lbl->setText(QString());
        ACModeM1lbl->setText(QApplication::translate("VehicleACPage", "\350\207\252\345\206\267", 0, QApplication::UnicodeUTF8));
        ACReduceM2lbl->setText(QString());
        ACModeM2lbl->setText(QApplication::translate("VehicleACPage", "\350\207\252\345\206\267", 0, QApplication::UnicodeUTF8));
        ACReduceMP2lbl->setText(QString());
        ACModeMP2lbl->setText(QApplication::translate("VehicleACPage", "\350\207\252\345\206\267", 0, QApplication::UnicodeUTF8));
        ACControlTC2lbl->setText(QApplication::translate("VehicleACPage", "\351\233\206\346\216\247", 0, QApplication::UnicodeUTF8));
        ACControlM2lbl->setText(QApplication::translate("VehicleACPage", "\351\233\206\346\216\247", 0, QApplication::UnicodeUTF8));
        ACControlMP2lbl->setText(QApplication::translate("VehicleACPage", "\351\233\206\346\216\247", 0, QApplication::UnicodeUTF8));
        ACControlM1lbl->setText(QApplication::translate("VehicleACPage", "\351\233\206\346\216\247", 0, QApplication::UnicodeUTF8));
        ACControlTC1lbl->setText(QApplication::translate("VehicleACPage", "\351\233\206\346\216\247", 0, QApplication::UnicodeUTF8));
        ACControlMP1lbl->setText(QApplication::translate("VehicleACPage", "\351\233\206\346\216\247", 0, QApplication::UnicodeUTF8));
        TempTC2lbl->setText(QApplication::translate("VehicleACPage", "23", 0, QApplication::UnicodeUTF8));
        TempM1lbl->setText(QApplication::translate("VehicleACPage", "23", 0, QApplication::UnicodeUTF8));
        TempTC1lbl->setText(QApplication::translate("VehicleACPage", "23", 0, QApplication::UnicodeUTF8));
        TempMP1lbl->setText(QApplication::translate("VehicleACPage", "23", 0, QApplication::UnicodeUTF8));
        TempMP2lbl->setText(QApplication::translate("VehicleACPage", "23", 0, QApplication::UnicodeUTF8));
        TempM2lbl->setText(QApplication::translate("VehicleACPage", "23", 0, QApplication::UnicodeUTF8));
        lbl1_14->setText(QString());
        YSJ1M2_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        YSJ1MP2_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        lbl1_15->setText(QString());
        YSJ1TC1_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        YSJ1MP1_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        YSJ1M1_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        YSJ1TC2_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        YSJ1MP2_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        YSJ1M2_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        YSJ1TC2_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        YSJ1TC1_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        YSJ1MP1_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        YSJ1M1_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        YSJ2TC1_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        YSJ2MP2_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        YSJ2MP1_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        YSJ2TC1_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        YSJ2M2_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        YSJ2M2_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        YSJ2M1_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        lbl1_16->setText(QString());
        YSJ2M1_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        YSJ2MP2_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        YSJ2TC2_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        YSJ2MP1_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        YSJ2TC2_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        LNFJ2TC2_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        LNFJ1M1_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        LNFJ1TC1_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        LNFJ1M1_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        LNFJ2MP2_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        lbl1_17->setText(QString());
        LNFJ1MP1_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        LNFJ2TC1_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        LNFJ2M2_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        lbl1_18->setText(QString());
        LNFJ1M2_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        LNFJ2M1_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        LNFJ1TC2_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        LNFJ1MP1_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        LNFJ1M2_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        LNFJ2TC1_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        LNFJ2TC2_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        LNFJ2MP1_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        LNFJ1TC1_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        LNFJ1TC2_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        LNFJ2M2_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        LNFJ2M1_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        LNFJ2MP1_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        LNFJ1MP2_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        LNFJ2MP2_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        LNFJ1MP2_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        TFJ2MP1_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        TFJ1M2_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        TFJ2M2_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        TFJ1TC2_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        TFJ1MP2_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        TFJ1MP1_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        TFJ1MP1_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        TFJ2MP2_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        TFJ2M1_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        TFJ1TC1_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        TFJ1TC2_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        TFJ2M1_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        TFJ1TC1_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        TFJ2TC1_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        TFJ1M2_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        TFJ2MP2_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        TFJ1M1_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        lbl1_19->setText(QString());
        TFJ2MP1_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        TFJ1M1_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        TFJ2M2_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        TFJ2TC2_1lbl->setText(QApplication::translate("VehicleACPage", "1", 0, QApplication::UnicodeUTF8));
        TFJ1MP2_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        lbl1_20->setText(QString());
        TFJ2TC2_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
        TFJ2TC1_2lbl->setText(QApplication::translate("VehicleACPage", "2", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class VehicleACPage: public Ui_VehicleACPage {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_VEHICLEACPAGE_H
